name: bpm

releases:
- name: bpm
  version: latest

instance_groups:
- name: bpm
  instances: 1
  azs: [z1, z2, z3]
  vm_type: default
  stemcell: default
  persistent_disk: 1024
  networks:
  - name: default
  jobs:
  - name: bpm
    release: bpm
  - name: test-server
    release: bpm
  - name: test-errand
    release: bpm

stemcells:
- alias: default
  os: ubuntu-bionic
  version: latest

update:
  canaries: 1
  canary_watch_time: 5000-120000
  max_in_flight: 1
  serial: false
  update_watch_time: 5000-120000
